Name: go-template-web
Host: 0.0.0.0
Port: 8888
Mode: dev #dev
Log:
  ServiceName: go-template-web
  Mode: file
  Path: ./logs
  Level: severe
  Compress: true
  KeepDays: 7
Mysql:
  Dsn: "user:pass@tcp(127.0.0.1:3306)/dbname?charset=utf8mb4&parseTime=True&loc=Local"
MongoDB:
  - DBName: go_template_mongo_1
    Dsn: "mongodb://admin:123456@127.0.0.1:27017/?minPoolSize=20&maxIdleTimeMS=30000"
  - DBName: go_template_mongo_2
    Dsn: "mongodb://admin:123456@127.0.0.1:27017/?minPoolSize=20&maxIdleTimeMS=30000"
