Name: game
Host: 0.0.0.0
Port: 8888
Mode: pro #dev|test|pre|pro
Log:
  ServiceName: game
  Mode: file
  Path: ./logs
  Level: info # info error severe
  Compress: true
  KeepDays: 30
MongoDB:
  - DBName: game_control_api
    Dsn: "mongodb://admin:123456@127.0.0.1:27017/?minPoolSize=20&maxIdleTimeMS=30000"

Secret: "tuz!TI+@ThZd!K5"